### ISSUE TITLE
Not able to throw when up against wall or obstacle

### ISSUE THREAD

**Issue by punkty** [qwerji/pewpews#3]
player === O
       wall === |

In the following situation the player is unable to throw left:
    <---  O|

The result is the sword colliding with the wall on the right and instantly picking up the sword again.

**Comment by qwerji** [comment]
on it boss

**Comment by qwerji** [comment]
Fixed by setting collisions for sword vs walls/obstacles only when the sword has a carrier but the sword's carrier doesn't have the sword, and setting an initial position when the sword is thrown.
